// Wagtail OS
// (c) Kristian Klomsten Skordal 2012 <kristian.skordal@gmail.com>
// Report bugs and issues on <http://github.com/skordal/wagtail>

#ifndef WAGTAIL_HARDWARE_SD_H
#define WAGTAIL_HARDWARE_SD_H

#include "hardware.h"

BEGIN_MODULE(sd)
	REGISTER_BEGIN(sysconfig, 0x000)
		BITNAME(autoidle, 0)
		BITNAME(softreset, 1)
	REGISTER_END()

	REGISTER_BEGIN(sysstatus, 0x014)
		BITNAME(resetdone, 0)
	REGISTER_END()

	REGISTER(arg, 0x108)

	REGISTER_BEGIN(con, 0x02c)
		BITNAME(clkextfree,	16)
		BITNAME(paden,		15)
		BITNAME(obie,		14)
		BITNAME(obip,		13)
		BITNAME(ceata,		12)
		BITNAME(ctpl,		11)
		BITNAME(wpp,		 8)
		BITNAME(cdp,		 7)
		BITNAME(mit,		 6)
		BITNAME(dw8,		 5)
		BITNAME(mode,		 4)
		BITNAME(str,		 3)
		BITNAME(hr,		 2)
		BITNAME(init,		 1)
		BITNAME(od,		 0)

		BITFIELD(dval,	9, 2)
	REGISTER_END()

	REGISTER(blk, 0x104)

	REGISTER(rsp10, 0x110)
	REGISTER(rsp32, 0x114)
	REGISTER(rsp54, 0x118)
	REGISTER(rsp76, 0x11c)

	REGISTER_BEGIN(cmd, 0x10c)
		BITNAME(dp,	21)
		BITNAME(cice,	20)
		BITNAME(ccce,	19)
		BITNAME(msbs,	 5)
		BITNAME(ddir,	 4)
		BITNAME(acen,	 2)
		BITNAME(bce,	 1)
		BITNAME(de,	 0)

		BITFIELD(rsp_type, 16, 2)
		BITFIELD(cmd_type, 22, 2)
		BITFIELD(indx, 24, 6)
	REGISTER_END()

	REGISTER(data, 0x120)

	REGISTER_BEGIN(pstate, 0x124)
		BITNAME(bre,	11)
		BITNAME(dati,	 1)
		BITNAME(cmdi,	 0)
	REGISTER_END()

	REGISTER_BEGIN(hctl, 0x128)
		BITNAME(obwe,	27)
		BITNAME(rem,	26)
		BITNAME(ins,	25)
		BITNAME(iwe,	24)
		BITNAME(ibg,	19)
		BITNAME(rwc,	18)
		BITNAME(cr,	17)
		BITNAME(sbgr,	16)
		BITNAME(sdbp,	 8)
		BITNAME(dtw,	 1)

		BITFIELD(sdvs, 9, 3)
	REGISTER_END()

	REGISTER_BEGIN(sysctl, 0x12c)
		BITNAME(srd,	26)
		BITNAME(src,	25)
		BITNAME(sra,	24)

		BITNAME(cen,	 2)
		BITNAME(ics,	 1)
		BITNAME(ice,	 0)
		
		BITFIELD(dto, 16, 4)
		BITFIELD(clkd, 6, 10)
	REGISTER_END()

	REGISTER_BEGIN(stat, 0x130)
		BITNAME(bada,	29)
		BITNAME(cerr,	28)
		BITNAME(ace,	24)
		BITNAME(deb,	22)
		BITNAME(dcrc,	21)
		BITNAME(dto,	20)
		BITNAME(cie,	19)
		BITNAME(ceb,	18)
		BITNAME(ccrc,	17)
		BITNAME(cto,	16)
		BITNAME(erri,	15)
		BITNAME(obi,	 9)
		BITNAME(cirq,	 8)
		BITNAME(brr,	 5)
		BITNAME(bwr,	 4)
		BITNAME(bge,	 2)
		BITNAME(tc,	 1)
		BITNAME(cc,	 0)
	REGISTER_END()

	REGISTER_BEGIN(ie, 0x134)
		BITNAME(bada,	29)
		BITNAME(cerr,	28)
		BITNAME(ace,	24)
		BITNAME(deb,	22)
		BITNAME(dcrc,	21)
		BITNAME(dto,	20)
		BITNAME(cie,	19)
		BITNAME(ceb,	18)
		BITNAME(ccrc,	17)
		BITNAME(cto,	16)
		BITNAME(null,	15)
		BITNAME(obi,	 9)
		BITNAME(cirq,	 8)
		BITNAME(brr,	 5)
		BITNAME(bwr,	 4)
		BITNAME(bge,	 2)
		BITNAME(tc,	 1)
		BITNAME(cc,	 0)
	REGISTER_END()

	REGISTER_BEGIN(ise, 0x138)
		BITNAME(bada,	29)
		BITNAME(cerr,	28)
		BITNAME(ace,	24)
		BITNAME(deb,	22)
		BITNAME(dcrc,	21)
		BITNAME(dto,	20)
		BITNAME(cie,	19)
		BITNAME(ceb,	18)
		BITNAME(ccrc,	17)
		BITNAME(cto,	16)
		BITNAME(null,	15)
		BITNAME(obi,	 9)
		BITNAME(cirq,	 8)
		BITNAME(brr,	 5)
		BITNAME(bwr,	 4)
		BITNAME(bge,	 2)
		BITNAME(tc,	 1)
		BITNAME(cc,	 0)
	REGISTER_END()

	REGISTER_BEGIN(capa, 0x140)
		BITNAME(hss,	21)
		BITNAME(ds,	22)
		BITNAME(srs,	23)
		BITNAME(vs33,	24)
		BITNAME(vs30,	25)
		BITNAME(vs18,	26)
	REGISTER_END()

	REGISTER_BEGIN(cur_capa, 0x148)
		BITFIELD(cur_1v8, 16, 8)
		BITFIELD(cur_3v0, 8, 8)
		BITFIELD(cur_3v3, 0, 8)
	REGISTER_END()
END_MODULE()

#endif

